# Import the OpenAI class from the openai library
from openai import OpenAI

# Initialize the OpenAI client with your API key
# Replace "sk-svcacct-" with your actual OpenAI API key
client = OpenAI(api_key="sk-svcacct-")

# Create a chat completion request
# This will generate a response based on the provided messages
completion = client.chat.completions.create(
  model="gpt-4o-mini", # Specify the AI model to use for generating responses
  messages=[ # Provide the context for the chat completion
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Give me 3 ideas for apps I could build with openai apis "}
  ]
)

# Print the response generated by the assistant
# Access the first choice from the completion response and print its message content
print(completion.choices[0].message)
